---
title: "Testing on simulated data"
author: "Andy Baxter"
format: 
  docx:
    number-sections: true
editor: visual
---

# Reading in simulated data

Data generated in Stata using methods in [Methods for dealing with time-dependent confounding](https://onlinelibrary.wiley.com/doi/10.1002/sim.5686).

```{r}
#| output: false

here::i_am("building_models/01_testing_methods_simuated_data.qmd")
df2 <- haven::read_dta("T:/projects/HEED/Data/heed_gform_example.dta")

source(here::here("R", "custom_helpers.R"))
library(tidyverse)
library(data.table)
library(gfoRmula)
library(gFormulaMI)

# Reshaping

dt2 <- df2 |> 
  rename(y3 = y) |> 
  mutate(id = row_number()) |> 
  select(-u) |> 
  pivot_longer(l0:y3, names_to = c("var", "t0"), values_to = "val", names_pattern = "(.)(.)") |> 
  pivot_wider(names_from = var, values_from = val) |> 
  mutate(t0 = as.integer(t0)) |> 
  as.data.table()
```

Table output in paper:

|  a0 |  a1 |  a2 |  a3 | Estimate |
|----:|----:|----:|----:|---------:|
|   0 |   0 |   0 |   0 |      2.1 |
|   0 |   0 |   0 |   1 |      1.6 |
|   0 |   0 |   1 |   0 |      1.6 |
|   0 |   0 |   1 |   1 |      1.1 |
|   0 |   1 |   0 |   0 |      1.6 |
|   0 |   1 |   0 |   1 |      1.1 |
|   0 |   1 |   1 |   0 |      1.1 |
|   0 |   1 |   1 |   1 |      0.6 |
|   1 |   0 |   0 |   0 |      1.6 |
|   1 |   0 |   0 |   1 |      1.1 |
|   1 |   0 |   1 |   0 |      1.1 |
|   1 |   0 |   1 |   1 |      0.6 |
|   1 |   1 |   0 |   0 |      1.1 |
|   1 |   1 |   0 |   1 |      0.6 |
|   1 |   1 |   1 |   0 |      0.6 |
|   1 |   1 |   1 |   1 |      0.1 |

# Test with `gfoRmula`

```{r}
time_points <- 4

# Complex interventions
intvars <-  as.list(rep("a", 16))

interventions <- tibble(a = 0:1, b = 0:1, c = 0:1, d = 0:1) |>
  expand.grid() |>
  arrange(a, b, c, d) |>
  t() |>
  as_tibble() |>
  unclass() |>
  map(~list(c(static, .x)))

int_description <-
  map(interventions, ~paste(.x[[1]][2:5], collapse = "-") |> paste0("Exposed:", x = _))


gf_out <- gformula(
  dt2,
  outcome_type = "continuous_eof", # eofu
  id = "id", # i(i)
  outcome_name = "y", # out(y)
  covnames = c("l", "a"), # com(y:regress, l:logit, a:logit)
  covtypes = c("binary", "binary"),  # see above
  covparams = list(
    covmodels = c(
      l ~ lag1_a*lag1_l,
      a ~ l*lag1_a
    )
  ),
  time_name = "t0", #t(t)
  time_points = time_points,
  intvars = intvars,
  interventions = interventions,
  int_descript = int_description,
  histories = c(lagged),
  histvars = list(c("a", "l")),
  ymodel = y ~ a + l + lag1_a + lag2_a + lag3_a + lag1_l + lag2_l + lag3_l ,
  seed = 1234,
  # parallel = TRUE,
  # nsamples = 200, # Number of bootstrap samples 
  nsimul = 2000
  # ncores = 6
)

gf_out$result |> 
  filter(Interv. != 0) |> 
  transmute(Intervention = int_description, Estimate = round(`g-form mean`, 1)) |> 
  knitr::kable()
```

# Test with gFormulaMI

```{r}

regimes <- tibble(a = 0:1, b = 0:1, c = 0:1, d = 0:1) |>
  expand.grid() |>
  arrange(a, b, c, d) |>
  # mutate(e = 0) |>
  t() |>
  as_tibble() |>
  unclass() |> unname()


imps <- gFormulaImpute(
  df2,
  M = 20,
  # nSim = 10000,
  trtVars = c("a0", "a1", "a2", "a3"),
  trtRegimes = regimes
)

library(magrittr)

fits <- imps %$%
  lm(y ~ factor(regime))

outvals <- syntheticPool(fits)

outvals |> 
  as_tibble() |> 
  rownames_to_column("Intervention") |> 
  mutate(
    Estimate = ifelse(Intervention == 1,
                           Estimate,  Estimate[Intervention == 1] + Estimate) |> round(1),
    Intervention = map(regimes, paste, collapse = "-")) |> 
  select(Intervention, Estimate) |> 
  knitr::kable()

```
