---
title: "Arranging baseline confounders"
author: "Andy Baxter"
execute: 
  echo: false
  output: false
  warning: false
format: 
  docx:
    number-sections: true
    reference-doc: reference.docx
---

# Reading in data


```{r setup}
#| output: false
here::i_am("building_models/02_simple_mcs_model_testing.qmd")
source(here::here("R", "data_import_and_cleaning.R"))

pop_data <- import_data() |> 
  data.table::as.data.table()

library(gfoRmula)
library(magrittr)
library(DiagrammeR)
library(gFormulaMI)
library(SPHSUgraphs)
library(tidyverse)
library(data.table)


ggplot2::theme_set(theme_sphsu_light())

# All observations with complete data across waves 8, 9 and 10

late_pop <- pop_data[wave %in% 8:10][, `:=`(
  t0 = t0 - 3,
  pre_mcs = shift(sf12mcs_dv, type = "lag"),
  pre_pcs = shift(sf12pcs_dv, type = "lag")
)][wave != 8]

missings <-
  late_pop[is.na(sf12mcs_dv) |
             is.na(sf12pcs_dv) | is.na(sex_dv_base) |
             is.na(hiqual_dv_base) | is.na(log_income) | is.na(home_owner_base) |
            is.na(wnw_race_base) | is.na(econ_emp_bin) | is.na(pre_mcs) |
             is.na(pre_pcs) | is.na(sf12mcs_dv_base) |
             is.na(sf12mcs_dv_base), .(pidp)]

late_pop <- late_pop[!missings, on = .(pidp)]

intervention_pattern <- expand_grid(0:1, 0:1) |>
  t() |>
  as_tibble(.name_repair = "minimal") |>
  unclass()
```

# Updating MCS and PCS from lags

```{r}
grViz("digraph {
  graph []
  node [fontname=Arial]
  A0 [label=<Empl<SUB>1</SUB>>]
  A1 [label=<Empl<SUB>2</SUB>>]
  I0 [label=<Inc<SUB>1</SUB>>]
  I1 [label=<Inc<SUB>2</SUB>>]
  M0 [label=<MCS<SUB>0</SUB>>]
  M1 [label=<MCS<SUB>1</SUB>>]
  L0 [label=<PCS<SUB>0</SUB>>]
  L1 [label=<PCS<SUB>1</SUB>>]
  Y [label=<<I>MCS<SUB>2</SUB></I>>]
  edge []
  M0 -> L0, A0, I0, M1
  L0 -> A0, I0, M1, L1
  A0 -> I0, M1, A1
  A0 -> L1 [constraint = false]
  I0 -> M1, L1, A1, I1
  M1 -> L1, A1, I1
  L1 -> A1, I1
  A1 -> I1
  M1, L1, A1, I1 -> Y
  {rank=min; M0, M1}
  {rank=same; L0, L1}
  {rank=same; A0, A1}
  {rank=max; I0, I1, Y}
}")
```

```{r}
outcome_type <- "continuous_eof"
outcome_name <- "sf12mcs_dv"
intvars <- c("econ_emp_bin")

time_points <- 2


covnames <-
  c(
    "econ_emp_bin",
    "pre_pcs",
    "pre_mcs",
    "log_income"
  )


covtypes <- c(
  "binary", # econ_emp_bin
  "normal", # pre_pcs
  "normal", # pre_mcs
  "normal" # log_income
)

ymodel <- sf12mcs_dv ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +  # Baseline - sex
  pre_pcs + pre_mcs +      # Time-varying confounders
  econ_emp_bin + log_income    # Time-varying exposures


covparams <- list(
  covmodels = c(
    econ_emp_bin ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      pre_mcs + pre_pcs + lag1_log_income + lag1_econ_emp_bin,
    pre_pcs ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      lag1_pre_pcs + pre_mcs + 
      lag1_econ_emp_bin + lag1_log_income,
    pre_mcs ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      lag1_pre_mcs + lag1_pre_mcs +
      lag1_econ_emp_bin + lag1_log_income,
    log_income ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      lag1_log_income + pre_pcs + pre_mcs + econ_emp_bin
  )
)



basecovs <- c(
  "sex_dv_base",
  "home_owner_base",
  "wnw_race_base",
  "hiqual_dv_base",
  "age_dv_base"
  # "gor_dv_base",
  # "dnc_base",
  # "mastat_dv_base",
)




lagged_variables <- c(
  "pre_pcs",
  "pre_mcs",
  "econ_emp_bin",
  "log_income"
)


histories <- c(lagged)
histvars <- list(lagged_variables)

nsimul <- 2000 # Monte Carlo sample size
ncores <- min(32, parallel::detectCores() - 1)



interventions <- intervention_pattern |>
  map( ~ list(c(static, .x)))

intvars <- as.list(rep("econ_emp_bin", length(interventions)))

int_description <-
  map(interventions, ~paste(.x[[1]][-1], collapse = "-") |> paste0("econ_emp_bin:", x = _))


gform_cont_eof <- gformula(obs_data = late_pop,
                           outcome_type = outcome_type,
                           id = "pidp",
                           time_name = "t0",
                           time_points = time_points,
                           covnames = covnames,
                           outcome_name = outcome_name,
                           covtypes = covtypes,
                           covparams = covparams,
                           # covpredict_custom = covpredict_custom,
                           ymodel = ymodel,
                           
                           intvars = intvars,
                           interventions = interventions,
                           int_descript = int_description,
                           
                           # covfits_custom = c(NA, NA, NA, NA, incr_fit),
                           # covpredict_custom = covpredict_custom,
                           
                           histories = histories,
                           histvars = histvars,
                           basecovs = basecovs,
                           seed = 1234,
                           parallel = FALSE,
                           # nsamples = 200, # Number of bootstrap samples
                           # nsimul = nsimul,
                           ref_int = 1
)

```

<!-- ## MI method -->

```{r}

regimes <- intervention_pattern

wide_data <- as_tibble(late_pop) |> 
  select(-wave, -contains("lag")) |> 
  pivot_wider(id_cols = c(pidp, ends_with("base")), names_from = t0, values_from = c(sf12mcs_dv:econ_dist, pre_mcs, pre_pcs)) |> 
  select(
    sex_dv_base,
    home_owner_base,
    wnw_race_base,
    hiqual_dv_base,
    age_dv_base,
    pre_mcs_0,
    pre_pcs_0,
    econ_emp_bin_0,
    log_income_0,
    pre_mcs_1,
    pre_pcs_1,
    econ_emp_bin_1,
    log_income_1,
    sf12mcs_dv_1
  )

pred_matrix <- 
matrix(c(
0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # sex_dv_base
0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # home_owner_base
0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # wnw_race_base
0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # hiqual_dv_base
0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # age_dv_base
1, 1, 1, 1, 1,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # pre_mcs_0
1, 1, 1, 1, 1,  1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # pre_pcs_0
1, 1, 1, 1, 1,  1, 1, 0, 0, 0, 0, 0, 0, 0, 0,  # econ_emp_bin_0
1, 1, 1, 1, 1,  1, 1, 1, 0, 0, 0, 0, 0, 0, 0,  # log_income_0
1, 1, 1, 1, 1,  1, 1, 1, 1, 0, 0, 0, 0, 0, 0,  # pre_mcs_1
1, 1, 1, 1, 1,  0, 1, 1, 1, 1, 0, 0, 0, 0, 0,  # pre_pcs_1
1, 1, 1, 1, 1,  0, 0, 1, 1, 1, 1, 0, 0, 0, 0,  # econ_emp_bin_1
1, 1, 1, 1, 1,  0, 0, 0, 1, 1, 1, 1, 0, 0, 0,  # log_income_1
1, 1, 1, 1, 1,  0, 0, 0, 0, 1, 1, 1, 1, 0, 0,  # sf12mcs_dv_1
1, 1, 1, 1, 1,  1, 1, 1, 1, 1, 1, 1, 1, 1, 0   # regime
), ncol = 15L, byrow = TRUE)

imps <- gFormulaImpute(
  wide_data,
  M = 40,
  trtVars = c("econ_emp_bin_0", "econ_emp_bin_1"),
  trtRegimes = regimes,
  predictorMatrix = pred_matrix
)


fits <- imps %$%
  lm(sf12mcs_dv_1 ~ factor(regime))

outvals <- syntheticPool(fits)

mi_results <-
  outvals |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(MI_result = ifelse(Intervention == 1,
                               Estimate,
                               Estimate[Intervention == 1] + Estimate)) |> 
  bind_rows(tibble(MI_result = NA_real_), x = _)
```

<!-- ## Manual method -->

```{r}

main_mod <- wide_data %$%
  lm(sf12mcs_dv_1 ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       pre_pcs_1 + pre_mcs_1 +
       log_income_1 + econ_emp_bin_1)

# All intervention populations set up
data_to_test <- expand_grid(econ_emp_bin_0 = 0:1, econ_emp_bin_1 = 0:1) |> 
  mutate(
    intervention = paste(econ_emp_bin_0, econ_emp_bin_1, sep = "-"),
    data_newvals = map2(econ_emp_bin_0, econ_emp_bin_1, \(a0, a1) mutate(wide_data, econ_emp_bin_0 = a0, econ_emp_bin_1 = a1))
  ) |> 
  bind_rows(
    tibble(intervention = "natural", data_newvals = list(wide_data)),
    x = _
  ) |> 
select(-econ_emp_bin_0, -econ_emp_bin_1)

# Models to update time-varying covariates at T=0 and T=1

mod_mcs0 <- wide_data %$%
  lm(pre_mcs_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base)

mod_pcs0 <- wide_data %$%
  lm(pre_pcs_0 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       pre_mcs_0
       )

mod_inc0 <- wide_data %$%
  lm(log_income_0 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       pre_mcs_0 + pre_pcs_0 + econ_emp_bin_0
       )


mod_mcs1 <- wide_data %$%
  lm(pre_mcs_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      pre_mcs_0 + pre_pcs_0 + econ_emp_bin_0 + log_income_0)

mod_pcs1 <- wide_data %$%
  lm(pre_pcs_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      pre_mcs_1 + pre_pcs_0 + econ_emp_bin_0 + log_income_0)

mod_inc1 <- wide_data %$%
  lm(log_income_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       pre_mcs_1 + pre_pcs_1 + econ_emp_bin_1 + log_income_0
       )

manual_results <- data_to_test |> 
  mutate(
    # Predict confounders at each time point based on prev vars
    data_newvals = map(data_newvals, ~mutate(.x, pre_mcs_0 = predict(mod_mcs0, newdata = .x))),
    data_newvals = map(data_newvals, ~mutate(.x, pre_pcs_0 = predict(mod_pcs0, newdata = .x))),
    data_newvals = map(data_newvals, ~mutate(.x, log_income_0 = predict(mod_inc0, newdata = .x))),
    data_newvals = map(data_newvals, ~mutate(.x, pre_mcs_1 = predict(mod_mcs1, newdata = .x))),
    data_newvals = map(data_newvals, ~mutate(.x, pre_pcs_1 = predict(mod_pcs1, newdata = .x))),
    data_newvals = map(data_newvals, ~mutate(.x, log_income_1 = predict(mod_inc1, newdata = .x))),
    # re-do predicton from main model based on updated confounders
    outcomes = map(data_newvals, ~predict(main_mod, newdata = .x)),
    # means of new values
    manual_result = map_dbl(outcomes, mean)
  ) |> 
  select(intervention, manual_result) 
```

## Comparing results

```{r}
#| output: true
out_results_mod1 <- gform_cont_eof$result |> 
  select(`g-form mean`) |>
  bind_cols(mi_results) |> 
  bind_cols(manual_results, x = _)

out_results_mod1 |> 
  knitr::kable(digits = 3)
  
```

```{r}
#| output: true
out_results_mod1 |> 
  pivot_longer(-intervention, names_to = "Calculation method", values_to = "estimate") |> 
  ggplot(aes(estimate, intervention, colour = `Calculation method`)) +
    geom_point(size = 3)  +
  scale_colour_sphsu()
```

# MCS baseline as static variable

```{r}
#| echo: false
grViz("digraph {
  graph []
  node [fontname=Arial]
  A0 [label=<Empl<SUB>1</SUB>>]
  A1 [label=<Empl<SUB>2</SUB>>]
  I0 [label=<Inc<SUB>1</SUB>>]
  I1 [label=<Inc<SUB>2</SUB>>]
  M0 [label=<MCS<SUB>0</SUB>> shape=rect]
  M1 [label='' color=none size = 0]
  L0 [label=<PCS<SUB>0</SUB>>]
  L1 [label=<PCS<SUB>1</SUB>>]
  Y [label=<<I>MCS<SUB>2</SUB></I>>]
  edge []
  M0 -> L0, A0, I0
  M0 -> L1, A1, I1, Y [constraint = false]
  # M0, A0, L0, I0 -> M1 -> L1, A1, I1, Y [color=yellow]
  L0 -> A0, I0, L1
  A0 -> I0, A1
  A0 -> L1 [constraint = false]
  I0 -> L1, A1, I1
  L1 -> A1, I1
  A1 -> I1
  L1, A1, I1 -> Y
  {rank=min; M0, M1}
  {rank=same; L0, L1}
  {rank=same; A0, A1}
  {rank=max; I0, I1, Y}
}")
```

<!-- ## `gfoRmula` -->

```{r}
outcome_type <- "continuous_eof"
outcome_name <- "sf12mcs_dv"
intvars <- c("econ_emp_bin")

time_points <- 2


ymodel <- sf12mcs_dv ~
  sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +  # Baseline - sex
  sf12mcs_dv_base +
  pre_pcs + # Time-varying confounders
  econ_emp_bin + log_income    # Time-varying exposures

covnames <-
  c(
    "econ_emp_bin",
    "pre_pcs",
    "log_income"
  )

covtypes <- c(
  "binary", # econ_emp_bin
  "normal", # sf12pcs_dv
  "normal" # log_income
)

covparams <- list(
  covmodels = c(
    econ_emp_bin ~ 
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      sf12mcs_dv_base +
      pre_pcs + lag1_log_income + 
      lag1_econ_emp_bin,
    pre_pcs ~ 
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      sf12mcs_dv_base +
      lag1_pre_pcs + 
      lag1_econ_emp_bin + lag1_log_income,
    log_income ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
      sf12mcs_dv_base +
      lag1_log_income + pre_pcs + econ_emp_bin
  )
)



basecovs <- c(
  "sex_dv_base",
  "home_owner_base",
  "wnw_race_base",
  "hiqual_dv_base",
  "age_dv_base",
  "sf12mcs_dv_base"
  # "gor_dv_base",
  # "dnc_base",
  # "mastat_dv_base",
)


lagged_variables <- c(
  "pre_pcs",
  "econ_emp_bin",
  "log_income"
  # "lag_mcs"
)


histories <- c(lagged)
histvars <- list(lagged_variables)

nsimul <- 2000 # Monte Carlo sample size
ncores <- min(32, parallel::detectCores() - 1)



interventions <- intervention_pattern |>
  map( ~ list(c(static, .x)))

intvars <- as.list(rep("econ_emp_bin", length(interventions)))

int_description <-
  map(interventions, ~paste(.x[[1]][-1], collapse = "-") |> paste0("econ_emp_bin:", x = _))


gform_cont_eof <- gformula(obs_data = late_pop,
                           outcome_type = outcome_type,
                           id = "pidp",
                           time_name = "t0",
                           time_points = time_points,
                           covnames = covnames,
                           outcome_name = outcome_name,
                           covtypes = covtypes,
                           covparams = covparams,
                           # covpredict_custom = covpredict_custom,
                           ymodel = ymodel,
                           
                           intvars = intvars,
                           interventions = interventions,
                           int_descript = int_description,
                           
                           # covfits_custom = c(NA, NA, NA, NA, incr_fit),
                           # covpredict_custom = covpredict_custom,
                           
                           histories = histories,
                           histvars = histvars,
                           basecovs = basecovs,
                           seed = 1234,
                           parallel = FALSE,
                           # nsamples = 200, # Number of bootstrap samples
                           # nsimul = nsimul,
                           ref_int = 1
)

gform_cont_eof
```


<!-- ## MI method -->

```{r}

regimes <- intervention_pattern

wide_data <- as_tibble(late_pop) |> 
  select(-wave, -contains("lag")) |> 
  pivot_wider(id_cols = c(pidp, ends_with("base")), names_from = t0, values_from = c(sf12mcs_dv:econ_dist, pre_mcs, pre_pcs)) |> 
  select(
    sex_dv_base,
    home_owner_base,
    wnw_race_base,
    hiqual_dv_base,
    age_dv_base,
    sf12mcs_dv_base,
    pre_pcs_0,
    econ_emp_bin_0,
    log_income_0,
    pre_pcs_1,
    econ_emp_bin_1,
    log_income_1,
    sf12mcs_dv_1
  )

pred_matrix <- 
matrix(c(
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # sex_dv_base
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # home_owner_base
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # wnw_race_base
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # hiqual_dv_base
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # age_dv_base
0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  # sf12mcs_dv_base
1, 1, 1, 1, 1, 1,  0, 0, 0, 0, 0, 0, 0, 0,  # pre_pcs_0
1, 1, 1, 1, 1, 1,  1, 0, 0, 0, 0, 0, 0, 0,  # econ_emp_bin_0
1, 1, 1, 1, 1, 1,  1, 1, 0, 0, 0, 0, 0, 0,  # log_income_0
1, 1, 1, 1, 1, 1,  1, 1, 1, 0, 0, 0, 0, 0,  # sf12pcs_dv_1
1, 1, 1, 1, 1, 1,  0, 1, 1, 1, 0, 0, 0, 0,  # econ_emp_bin_1
1, 1, 1, 1, 1, 1,  0, 0, 1, 1, 1, 0, 0, 0,  # log_income_1
1, 1, 1, 1, 1, 1,  0, 0, 0, 1, 1, 1, 0, 0,  # pre_pcs_1
1, 1, 1, 1, 1, 1,  1, 1, 1, 1, 1, 1, 1, 0   # regime
), ncol = 14L, byrow = TRUE)

imps <- gFormulaImpute(
  wide_data,
  M = 40,
  trtVars = c("econ_emp_bin_0", "econ_emp_bin_1"),
  trtRegimes = regimes,
  predictorMatrix = pred_matrix
)


fits <- imps %$%
  lm(sf12mcs_dv_1 ~ factor(regime))

outvals <- syntheticPool(fits)

mi_results <-
  outvals |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(MI_result = ifelse(Intervention == 1,
                               Estimate,
                               Estimate[Intervention == 1] + Estimate)) |> 
  bind_rows(tibble(MI_result = NA_real_), x = _)
```

<!-- ## Manual method -->

```{r}

main_mod <- wide_data %$%
  lm(sf12mcs_dv_1 ~ sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       sf12mcs_dv_base +
       log_income_1 + econ_emp_bin_1 + pre_pcs_1)

# All intervention populations set up
data_to_test <- expand_grid(econ_emp_bin_0 = 0:1, econ_emp_bin_1 = 0:1) |> 
  mutate(
    intervention = paste(econ_emp_bin_0, econ_emp_bin_1, sep = "-"),
    data_newvals = map2(econ_emp_bin_0, econ_emp_bin_1, \(a0, a1) mutate(wide_data, econ_emp_bin_0 = a0, econ_emp_bin_1 = a1))
  ) |> 
  bind_rows(
    tibble(intervention = "natural", data_newvals = list(wide_data)),
    x = _
  ) |> 
select(-econ_emp_bin_0, -econ_emp_bin_1)

# Models to update time-varying covariates at T=0
mod_inc0 <- wide_data %$%
  lm(log_income_0 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       sf12mcs_dv_base +
      pre_pcs_0 + econ_emp_bin_0
       )

# mod_mcs0 <- wide_data %$%
#   lm(sf12mcs_dv_0 ~
#       sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
#        sf12mcs_dv_base +
#       sf12pcs_dv_0 + econ_emp_bin_0 + log_income_0
#        )

mod_pcs1 <- wide_data %$%
  lm(pre_pcs_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       sf12mcs_dv_base +
      pre_pcs_0 + econ_emp_bin_0 + log_income_0)

mod_inc1 <- wide_data %$%
  lm(log_income_1 ~
      sex_dv_base + home_owner_base + wnw_race_base + hiqual_dv_base + age_dv_base +
       sf12mcs_dv_base +
       econ_emp_bin_1 + log_income_0 + pre_pcs_1
       )

manual_results <- data_to_test |> 
  mutate(
    # Predict confounders at each time point based on prev vars
    data_update = map(data_newvals, ~mutate(.x, log_income_0 = predict(mod_inc0, newdata = .x))),
    # data_update = map(data_update, ~mutate(.x, sf12mcs_dv_0 = predict(mod_mcs0, newdata = .x))),
    data_update = map(data_update, ~mutate(.x, sf12pcs_dv_1 = predict(mod_pcs1, newdata = .x))),
    data_update = map(data_update, ~mutate(.x, log_income_1 = predict(mod_inc1, newdata = .x))),
    # re-do predicton from main model based on updated confounders
    outcomes = map(data_update, ~predict(main_mod, newdata = .x)),
    # means of new values
    manual_result = map_dbl(outcomes, mean)
  ) |> 
  select(intervention, manual_result) 
```

## Comparing results

```{r}
#| output: true
out_results_mod2 <- gform_cont_eof$result |> 
  select(`g-form mean`) |>
  bind_cols(mi_results) |> 
  bind_cols(manual_results, x = _)

out_results_mod2 |> 
  knitr::kable(digits = 3)
  
```

```{r}
#| output: true
out_results_mod2 |> 
  pivot_longer(-intervention, names_to = "Calculation method", values_to = "estimate") |> 
  ggplot(aes(estimate, intervention, colour = `Calculation method`)) +
    geom_point(size = 3)  +
  scale_colour_sphsu()
```

# Combined results

```{r}
#| output: true
library(gt)

tibble(
  model = c("Model 1", "Model 2"),
  results = list(out_results_mod1, out_results_mod2)
) |> 
  unnest(results) |> 
  mutate(
    `Manual calculation` = manual_result,
    `gfoRmula package` = `g-form mean`,
    `gFormulaMI package` = MI_result,
    .keep = "unused"
  ) |> 
  pivot_wider(names_from = model, names_glue = "{model}_{.value}", values_from = `Manual calculation`:`gFormulaMI package`, names_sort = TRUE) |> 
  select(intervention, starts_with("Model 1"), starts_with("Model 2")) |> 
  gt() |> 
  fmt_number() |> 
  tab_spanner_delim("_")
```


```{r}
#| output: true
tibble(
  model = c("Model 1", "Model 2"),
  results = list(out_results_mod1, out_results_mod2)
) |> 
  unnest(results) |> 
  mutate(
    `Manual calculation` = manual_result,
    `gfoRmula package` = `g-form mean`,
    `gFormulaMI package` = MI_result,
    .keep = "unused"
  ) |> 
  pivot_longer(-c(model, intervention), names_to = "Calculation method", values_to = "estimate") |> 
  ggplot(aes(estimate, intervention, colour = `Calculation method`)) +
    geom_point(size = 3)  +
  scale_colour_sphsu() + 
  facet_wrap(~model, ncol = 1)
```

