---
title: "Estimating three-period with baseline and accumulating variables"
author: "Andy Baxter"
format: 
  html:
    toc: true
    fig-format: svg
execute: 
  output: false
---

# Setup

```{r setup}
#| output: false
here::i_am("building_models/11_new_workflow.qmd")
source(here::here("R", "data_import_and_cleaning.R"))
source(here::here("R", "func_prep_data.R"))

library(gfoRmula)
library(gFormulaMI)
library(magrittr)
library(SPHSUgraphs)
library(tidyverse)
library(data.table)
library(DiagrammeR)

pop_data <- import_data() |> 
  select(-econ_incquint) 

ggplot2::theme_set(theme_sphsu_light())

# Filter for only those observed at wave 2 (baseline), and wave 6

pop_dt <- pop_data |> 
  filter(wave == 2, response == 1) |> 
  select(pidp) |> 
  left_join(pop_data, by = "pidp") |> 
  filter(wave == 6, response == 1) |> 
  select(pidp) |> 
  left_join(pop_data, by = "pidp") |> 
  filter(!is.na(mastat_dv_base)) |> 
  mutate(dnc = factor(dnc) |> fct_collapse(zero = "0", one = "1", other_level = "2+")) |> 
  data.table::as.data.table()

long_data <- pop_dt[, `:=`(
  t0 = t0 - 2,
  pre_mcs = shift(sf12mcs_dv, type = "lag"),
  pre_pcs = shift(sf12pcs_dv, type = "lag"),
  mcs_outcome = sf12mcs_dv,
  pcs_outcome = sf12pcs_dv
)][wave %in% 3:6]

no_mh_outcomes <- long_data |> 
  group_by(pidp) |> 
  summarise(n_missing = sum(is.na(sf12mcs_dv)), base_missing = all(is.na(sf12mcs_dv_base))) |> 
  filter(n_missing == 2, base_missing) |> 
  select(pidp) |> 
  as.data.table()

long_data <- long_data[!no_mh_outcomes, on = .(pidp)] 

intervention_pattern_2 <- expand_grid(0:1, 0:1) |>
  t() |>
  as_tibble(.name_repair = "minimal") |>
  unclass()

intervention_pattern_3 <- expand_grid(0:1, 0:1, 0:1) |>
  t() |>
  as_tibble(.name_repair = "minimal") |>
  unclass()

intervention_pattern_4 <- expand_grid(0:1, 0:1, 0:1, 0:1) |>
  t() |>
  as_tibble(.name_repair = "minimal") |>
  unclass()

ncores <- 2

nsamples <- 100

# Setup wide data for MI

wide_data <- long_data |>
  mutate(econ_emp_bin = as_factor(econ_emp_bin)) |> 
  make_wide(
    pidp,
    t0,
    base_cols = c(sex_dv_base,
                  wnw_race_base,
                  hiqual_dv_base,
                  age_dv_base,
                  gor_dv_base,
                  mastat_dv_base,
                  sf12mcs_dv_base),
    outcome = sf12mcs_dv,
    sf12pcs_dv,
    econ_emp_bin,
    log_income,
    dnc,
    home_owner,
    econ_benefits,
    econ_dist,
    sf12mcs_dv
  )

wide_mids <- mice::mice(wide_data, defaultMethod = c("norm", "logreg", "pmm", "pmm"), m = 35, maxit = 10)
#wide_mids <- readRDS(here::here("data", "wide_mids_full_models_MI_only.rds"))

base_predictor_matrix <- make_predictor_matrix(wide_data)
```

# Four periods of intervention - dynamic baseline

## gFormulaMI

```{r 4cummulative-mi}
regimes <- intervention_pattern_4

predictor_matrix <- base_predictor_matrix

# predictor_matrix["sf12mcs_dv_0",] <- 0
# predictor_matrix["sf12mcs_dv_1",] <- 0
# predictor_matrix["sf12mcs_dv_2",] <- 0
# predictor_matrix["sf12mcs_dv_3",] <- 0

# MCS does not predict intermediate outcomes
predictor_matrix[,"sf12mcs_dv_0"] <- 0
predictor_matrix[,"sf12mcs_dv_1"] <- 0
predictor_matrix[,"sf12mcs_dv_2"] <- 0
predictor_matrix[,"sf12mcs_dv_3"] <- 0

# MCS is dependent on previous MCS values
predictor_matrix["sf12mcs_dv_1","sf12mcs_dv_0"] <- 1
predictor_matrix["sf12mcs_dv_2","sf12mcs_dv_1"] <- 1
predictor_matrix["sf12mcs_dv_3","sf12mcs_dv_2"] <- 1

# MCS is not predicted by baseline MCS
predictor_matrix["sf12mcs_dv_1","sf12mcs_dv_base"] <- 0
predictor_matrix["sf12mcs_dv_2","sf12mcs_dv_base"] <- 0
predictor_matrix["sf12mcs_dv_3","sf12mcs_dv_base"] <- 0

imps <- gFormulaImpute(
  wide_mids,
  trtVars = c("econ_emp_bin_0", "econ_emp_bin_1", "econ_emp_bin_2", "econ_emp_bin_3"),
  trtRegimes = regimes,
  predictorMatrix = predictor_matrix
)

fits <- imps %$%
  lm(sf12mcs_dv_3 ~ 0 + factor(regime))

mi_4cummulative <- syntheticPool(fits)

regimes_4 <- tibble(intervention = regimes |> 
  map(paste, collapse = "-") |> 
  reduce(c)
)
```

## Table with estimates

```{r 4cummulative-tab}
#| output: true

mod_4cummulative <- mi_4cummulative |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(mi_effect = Estimate,
            mi_se = sqrt(Total),
            mi_ll = `95% CI L`,
            mi_ul = `95% CI U`) |>
  bind_cols(regimes_4)

mod_4cummulative |> 
  knitr::kable(digits = 3)
  
```

```{r 4cummulative-graph}
#| output: true
mod_4cummulative |>
  pivot_longer(
    -intervention,
    names_to = c("Calculation method", ".value"),
    names_pattern = "(.*)_(.*)"
  ) |>
  mutate(n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |>
           factor()) |> 
ggplot(aes(effect, intervention, shape = `Calculation method`, xmin = ll, xmax = ul,
    colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7))  +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_brewer(name = "Number of unemployed periods", palette = "Set1") +
  facet_wrap(~`Calculation method`, ncol = 1)
```


<!-- # If this does not work, include the lagged vars in the make_wide step above -->