---
title: "Results: Five Waves of Intervention"
author: "Darwin Del Castillo"
format:
  html:
    toc: true
    fig-format: svg
execute:
  output: false
---

```{r env-setup}
#| output: false
#| message: false
options(max.print = 999999)
here::i_am("building_models/18_five_waves_final.qmd")
source(here::here("R", "import_and_clean.R"))
source(here::here("R", "func_prep_data.R"))

pacman::p_load(data.table, here, mice, gFormulaMI, magrittr, tidyverse)

seed <- 20260410
```

```{r prep-data}
#| message: false
#| warning: false

pop_data <- clean_data() |> preproc_data()

# keep only people observed at both wave 2 (pre-baseline, for lagged in w3) and wave 7 (outcome)
eligible_pidp <- intersect(
  pop_data[wave == 2 & response == 1, pidp],
  pop_data[wave == 7 & response == 1, pidp]
)

pop_DT <- pop_data[pidp %in% eligible_pidp]

# long format variable shifting
long_data <- pop_DT[, `:=`(
  t0 = t0 - 2L,
  pcs_lagged = shift(sf12pcs_dv, type = "lag"),
  mcs_lagged = shift(sf12mcs_dv, type = "lag"),
# the other time-varying confounders should also be lagged
  lagged_dnc = shift(dnc, type = "lag"),
  lagged_home_owner = shift(home_owner, type = "lag"),
  lagged_econ_benefits = shift(econ_benefits, type = "lag"),
  lagged_gor_dv_fact = shift(gor_dv_fact, type = "lag"),
  lagged_age_dv = shift(age_dv, type = "lag"),
  lagged_mastat_dv = shift(mastat_dv, type = "lag")
  )][wave %in% 3:7]

# keeping those with at least 2 observed MCS outcomes and no baseline missing
no_mh_outcomes <- long_data[,
  .(n_missing = sum(is.na(sf12mcs_dv)), base_missing = all(is.na(sf12mcs_dv_base))),
  by = pidp
][n_missing >= 2 & base_missing == TRUE, .(pidp)]

long_data <- long_data[!no_mh_outcomes, on = .(pidp)]

# matrix of possible intervention patterns for 5 time points (0: no intervention, 1: intervention)
intervention_pattern_5 <- asplit(as.matrix(CJ(0:1, 0:1, 0:1, 0:1, 0:1)), 1)
```

# MCS outcome

```{r prep-data-wide-mcs}
# wide format for gformulaMI
wide_data_mcs <- long_data |>
  mutate(econ_emp_bin = as_factor(econ_emp_bin)) |>
  make_wide(
    pidp,
    t0,
    base_cols = c(sex_dv_base, # wave 1
                  race_base, # wave 1
                  hiqual_dv_base, # wave 1
                  sf12mcs_dv_base # wave 1
                  ),
    outcome = sf12mcs_dv,
    pcs_lagged,
    econ_emp_bin,
    log_income,
    lagged_dnc,
    lagged_home_owner,
    lagged_econ_benefits,
    lagged_mastat_dv,
    lagged_age_dv,
    lagged_gor_dv_fact, # wave 1
    econ_dist,
    static = FALSE,
    waves = c(0,1,2,3,4)
  )
```

```{r multiple-imputation-mcs}
pred_mat <- make.predictorMatrix(wide_data_mcs)

pred_mat[,c("lagged_age_dv_0", "lagged_age_dv_1", "lagged_age_dv_2", "lagged_age_dv_3", "lagged_age_dv_4")] <- 0 # collinearity
pred_mat[,c("lagged_gor_dv_fact_0", "lagged_gor_dv_fact_1", "lagged_gor_dv_fact_2", "lagged_gor_dv_fact_3", "lagged_gor_dv_fact_4")] <- 0 # collinearity across levels of the factor

if (file.exists(here::here("output", "wide_mids_mcs_5w.rds"))) {
  wide_mids_mcs <- readRDS(here::here("output", "wide_mids_mcs_5w.rds"))
  message("Loading existing observed outcomes for MCS g-formulaMI run...")
} else {
  message("No existing observed outcomes found. Running multiple imputation for MCS outcome with 5 waves of intervention...")
wide_mids_mcs <- mice(
    wide_data_mcs,
    predictorMatrix = pred_mat,
    defaultMethod = c("norm", "logreg", "pmm", "pmm"),
    m = 60,
    maxit = 15,
    seed = seed
    )
saveRDS(wide_mids_mcs, here::here("output", "wide_mids_mcs_5w.rds"))
}
rm(wide_mids_mcs) # to save memory
base_predictor_matrix_mcs <- make_predictor_matrix(wide_data_mcs) # custom g-formulaMI predictor matrix function
```

## gFormulaMI run

```{r gformulaMI-mcs}
regimes <- intervention_pattern_5

predictor_matrix <- base_predictor_matrix_mcs

# MCS does not predict intermediate outcomes
predictor_matrix[,"sf12mcs_dv_0"] <- 0
predictor_matrix[,"sf12mcs_dv_1"] <- 0
predictor_matrix[,"sf12mcs_dv_2"] <- 0
predictor_matrix[,"sf12mcs_dv_3"] <- 0

# MCS is dependent on previous MCS values
predictor_matrix["sf12mcs_dv_1","sf12mcs_dv_0"] <- 1
predictor_matrix["sf12mcs_dv_2","sf12mcs_dv_1"] <- 1
predictor_matrix["sf12mcs_dv_3","sf12mcs_dv_2"] <- 1
predictor_matrix["sf12mcs_dv_4","sf12mcs_dv_3"] <- 1

# MCS is not predicted by baseline MCS, only by their immediate previous value
predictor_matrix["sf12mcs_dv_1","sf12mcs_dv_base"] <- 0
predictor_matrix["sf12mcs_dv_2","sf12mcs_dv_base"] <- 0
predictor_matrix["sf12mcs_dv_3","sf12mcs_dv_base"] <- 0
predictor_matrix["sf12mcs_dv_4","sf12mcs_dv_base"] <- 0

# MCS in period t (not baseline) predicts employment and income in the period t+1
predictor_matrix["sf12mcs_dv_0",c("econ_emp_bin_1", "log_income_1")] <- 1
predictor_matrix["sf12mcs_dv_1",c("econ_emp_bin_2", "log_income_2")] <- 1
predictor_matrix["sf12mcs_dv_2",c("econ_emp_bin_3", "log_income_3")] <- 1
predictor_matrix["sf12mcs_dv_3",c("econ_emp_bin_4", "log_income_4")] <- 1

# Economic distress does not affect income or employment of the next period
predictor_matrix["econ_dist_0",c("econ_emp_bin_1", "log_income_1")] <- 0
predictor_matrix["econ_dist_1",c("econ_emp_bin_2", "log_income_2")] <- 0
predictor_matrix["econ_dist_2",c("econ_emp_bin_3", "log_income_3")] <- 0
predictor_matrix["econ_dist_3",c("econ_emp_bin_4", "log_income_4")] <- 0

# MCS in wave t predicts employment at time t+1
predictor_matrix["econ_emp_bin_1", "sf12mcs_dv_0"] <- 1
predictor_matrix["econ_emp_bin_2", "sf12mcs_dv_1"] <- 1
predictor_matrix["econ_emp_bin_3", "sf12mcs_dv_2"] <- 1
predictor_matrix["econ_emp_bin_4", "sf12mcs_dv_3"] <- 1

# regime row always needs to be 1
predictor_matrix["regime",] <- 1

if (file.exists(here::here("output", "imps_mcs_5w.rds"))) {
  imps_mcs <- readRDS(here::here("output", "imps_mcs_5w.rds"))
  message("Loading existing imputations for MCS g-formulaMI run...")
} else {
wide_mids_mcs <- readRDS(here::here("output", "wide_mids_mcs_5w.rds"))
message(sprintf("wide_mids_mcs loaded: %s", format(object.size(wide_mids_mcs), units = "MB")))
message("No existing synthetic counterfactual imputations found. Running g-formulaMI for MCS outcome with 5 waves of intervention...")
imps_mcs <- gFormulaImpute(
    wide_mids_mcs,
    trtVars = c("econ_emp_bin_0", "econ_emp_bin_1", "econ_emp_bin_2", "econ_emp_bin_3", "econ_emp_bin_4"),
    trtRegimes = regimes,
    predictorMatrix = predictor_matrix,
    M = 200,
    silent = TRUE
  )
message(sprintf("imps_mcs created: %s", format(object.size(imps_mcs), units = "MB")))
saveRDS(imps_mcs, here::here("output", "imps_mcs_5w.rds"))
rm(wide_mids_mcs); gc()
message("wide_mids_mcs removed and GC run")
}

fits_marginal_mcs <- imps_mcs %$%
  lm(sf12mcs_dv_4 ~ 0 + factor(regime))

fits_diff_mcs <- imps_mcs %$%
  lm(sf12mcs_dv_4 ~ factor(regime))

mi_5cummulative_mcs_marginal <- syntheticPool(fits_marginal_mcs)
mi_5cummulative_mcs_diff <- syntheticPool(fits_diff_mcs)

rm(imps_mcs, fits_marginal_mcs, fits_diff_mcs) # to save memory
```

```{r 5wavesmi-regimes-common}
regimes_5 <- tibble(intervention = regimes |>
  map(paste, collapse = "-") |>
  reduce(c)
)
```

## Table

```{r 5wavesmi-tab-mcs}
#| output: true
mod_5cummulative_mcs_marginal <- mi_5cummulative_mcs_marginal |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(mi_effect = Estimate,
            mi_se = sqrt(Total),
            mi_ll = `95% CI L`,
            mi_ul = `95% CI U`) |>
  bind_cols(regimes_5)

mod_5cummulative_mcs_marginal |>
  knitr::kable(digits = 3)

mod_5cummulative_mcs_diff <- mi_5cummulative_mcs_diff |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(mi_effect = Estimate,
            mi_se = sqrt(Total),
            mi_ll = `95% CI L`,
            mi_ul = `95% CI U`) |>
  bind_cols(regimes_5)

mod_5cummulative_mcs_diff |>
  knitr::kable(digits = 3)

saveRDS(mod_5cummulative_mcs_marginal, here::here("output", "model_5w_mcs_marginal.rds"))
saveRDS(mod_5cummulative_mcs_diff, here::here("output", "model_5w_mcs_diff.rds"))

# deleting objects to save memory for the next outcome
rm(mi_5cummulative_mcs_marginal, mi_5cummulative_mcs_diff, mod_5cummulative_mcs_marginal, mod_5cummulative_mcs_diff)
```

# PCS outcome

```{r prep-data-wide-pcs}
wide_data_pcs <- long_data |>
  mutate(econ_emp_bin = as_factor(econ_emp_bin)) |>
  make_wide(
    pidp,
    t0,
    base_cols = c(sex_dv_base, # wave 1
                  race_base, # wave 1
                  hiqual_dv_base, # wave 1
                  sf12pcs_dv_base # wave 1
                  ),
    outcome = sf12pcs_dv,
    mcs_lagged,
    econ_emp_bin,
    log_income,
    lagged_dnc,
    lagged_home_owner,
    lagged_econ_benefits,
    lagged_mastat_dv,
    lagged_age_dv,
    lagged_gor_dv_fact,
    econ_dist,
    static = FALSE,
    waves = c(0,1,2,3,4)
  )
```

```{r multiple-imputation-pcs}
pred_mat_pcs <- make.predictorMatrix(wide_data_pcs)

pred_mat_pcs[,c("lagged_age_dv_0", "lagged_age_dv_1", "lagged_age_dv_2", "lagged_age_dv_3", "lagged_age_dv_4")] <- 0 # collinearity
pred_mat_pcs[,c("lagged_gor_dv_fact_0", "lagged_gor_dv_fact_1", "lagged_gor_dv_fact_2", "lagged_gor_dv_fact_3", "lagged_gor_dv_fact_4")] <- 0 # collinearity across levels of the factor

if (file.exists(here::here("output", "wide_mids_pcs_5w.rds"))) {
  wide_mids_pcs <- readRDS(here::here("output", "wide_mids_pcs_5w.rds"))
  message("Loading existing observed outcomes for PCS g-formulaMI run...")
} else {
  message("No existing observed outcomes found. Running multiple imputation for PCS outcome with 5 waves of intervention...")
wide_mids_pcs <- mice(
    wide_data_pcs,
    predictorMatrix = pred_mat_pcs,
    defaultMethod = c("norm", "logreg", "pmm", "pmm"),
    m = 50,
    maxit = 15,
    seed = seed
    )
saveRDS(wide_mids_pcs, here::here("output", "wide_mids_pcs_5w.rds"))
}

base_predictor_matrix_pcs <- make_predictor_matrix(wide_data_pcs) # custom g-formulaMI predictor matrix function
```

```{r gformulaMI-pcs}
# predictor matrix for PCS g-formulaMI run
predictor_matrix_pcs <- base_predictor_matrix_pcs

# PCS does not predict intermediate outcomes
predictor_matrix_pcs[,"sf12pcs_dv_0"] <- 0
predictor_matrix_pcs[,"sf12pcs_dv_1"] <- 0
predictor_matrix_pcs[,"sf12pcs_dv_2"] <- 0
predictor_matrix_pcs[,"sf12pcs_dv_3"] <- 0

# PCS is dependent on previous PCS values
predictor_matrix_pcs["sf12pcs_dv_1","sf12pcs_dv_0"] <- 1
predictor_matrix_pcs["sf12pcs_dv_2","sf12pcs_dv_1"] <- 1
predictor_matrix_pcs["sf12pcs_dv_3","sf12pcs_dv_2"] <- 1
predictor_matrix_pcs["sf12pcs_dv_4","sf12pcs_dv_3"] <- 1

# PCS is not predicted by baseline PCS, only by their immediate previous value
predictor_matrix_pcs["sf12pcs_dv_1","sf12pcs_dv_base"] <- 0
predictor_matrix_pcs["sf12pcs_dv_2","sf12pcs_dv_base"] <- 0
predictor_matrix_pcs["sf12pcs_dv_3","sf12pcs_dv_base"] <- 0
predictor_matrix_pcs["sf12pcs_dv_4","sf12pcs_dv_base"] <- 0

# PCS in period t (not baseline) predicts employment and income in the period t+1
predictor_matrix_pcs["sf12pcs_dv_0",c("econ_emp_bin_1", "log_income_1")] <- 1
predictor_matrix_pcs["sf12pcs_dv_1",c("econ_emp_bin_2", "log_income_2")] <- 1
predictor_matrix_pcs["sf12pcs_dv_2",c("econ_emp_bin_3", "log_income_3")] <- 1
predictor_matrix_pcs["sf12pcs_dv_3",c("econ_emp_bin_4", "log_income_4")] <- 1

# Economic distress does not affect income or employment of the next period
predictor_matrix_pcs["econ_dist_0",c("econ_emp_bin_1", "log_income_1")] <- 0
predictor_matrix_pcs["econ_dist_1",c("econ_emp_bin_2", "log_income_2")] <- 0
predictor_matrix_pcs["econ_dist_2",c("econ_emp_bin_3", "log_income_3")] <- 0
predictor_matrix_pcs["econ_dist_3",c("econ_emp_bin_4", "log_income_4")] <- 0

# PCS in wave t predicts employment at time t+1
predictor_matrix_pcs["econ_emp_bin_1", "sf12pcs_dv_0"] <- 1
predictor_matrix_pcs["econ_emp_bin_2", "sf12pcs_dv_1"] <- 1
predictor_matrix_pcs["econ_emp_bin_3", "sf12pcs_dv_2"] <- 1
predictor_matrix_pcs["econ_emp_bin_4", "sf12pcs_dv_3"] <- 1

# regime row always needs to be 1
predictor_matrix_pcs["regime",] <- 1

if (file.exists(here::here("output", "imps_pcs_5w.rds"))) {
  imps_pcs <- readRDS(here::here("output", "imps_pcs_5w.rds"))
  message("Loading existing imputations for PCS g-formulaMI run...")
} else {
imps_pcs <- gFormulaImpute(
    wide_mids_pcs,
    trtVars = c("econ_emp_bin_0", "econ_emp_bin_1", "econ_emp_bin_2", "econ_emp_bin_3", "econ_emp_bin_4"),
    trtRegimes = regimes,
    predictorMatrix = predictor_matrix_pcs,
    M = 200,
    silent = TRUE
  )
saveRDS(imps_pcs, here::here("output", "imps_pcs_5w.rds"))
}

rm(wide_mids_pcs) # to save memory

fits_marginal_pcs <- imps_pcs %$%
  lm(sf12pcs_dv_4 ~ 0 + factor(regime))

fits_diff_pcs <- imps_pcs %$%
  lm(sf12pcs_dv_4 ~ factor(regime))

mi_5cummulative_pcs_marginal <- syntheticPool(fits_marginal_pcs)
mi_5cummulative_pcs_diff <- syntheticPool(fits_diff_pcs)

rm(imps_pcs, fits_marginal_pcs, fits_diff_pcs) # to save memory
```

## Table

```{r 5wavesmi-tab-pcs}
#| output: true
mod_5cummulative_pcs_marginal <- mi_5cummulative_pcs_marginal |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(mi_effect = Estimate,
            mi_se = sqrt(Total),
            mi_ll = `95% CI L`,
            mi_ul = `95% CI U`) |>
  bind_cols(regimes_5)

mod_5cummulative_pcs_marginal |>
  knitr::kable(digits = 3)

mod_5cummulative_pcs_diff <- mi_5cummulative_pcs_diff |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(mi_effect = Estimate,
            mi_se = sqrt(Total),
            mi_ll = `95% CI L`,
            mi_ul = `95% CI U`) |>
  bind_cols(regimes_5)

mod_5cummulative_pcs_diff |>
  knitr::kable(digits = 3)

saveRDS(mod_5cummulative_pcs_marginal, here::here("output", "model_5w_pcs_marginal.rds"))
saveRDS(mod_5cummulative_pcs_diff, here::here("output", "model_5w_pcs_diff.rds"))

# deleting objects to save memory for the next outcome
rm(mi_5cummulative_pcs_marginal, mi_5cummulative_pcs_diff, mod_5cummulative_pcs_marginal, mod_5cummulative_pcs_diff)
```

# Graphs

## Marginal estimates

```{r 5wavesmi-graph-marginal}
#| output: true
mod_5cummulative_mcs_marginal <- readRDS(here::here("output", "model_5w_mcs_marginal.rds"))

mod_5cummulative_pcs_marginal <- readRDS(here::here("output", "model_5w_pcs_marginal.rds"))

graph5waves_marginal <- bind_rows(
  mod_5cummulative_mcs_marginal |> mutate(outcome = "MCS"),
  mod_5cummulative_pcs_marginal |> mutate(outcome = "PCS")
) |>
  mutate(
    n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |> factor(),
    intervention = str_replace_all(intervention, c("0" = "E", "1" = "U"))
  ) |>
  ggplot(aes(mi_effect, intervention, xmin = mi_ll, xmax = mi_ul, colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7)) +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_brewer(name = "Number of unemployed periods", palette = "Set1") +
  facet_wrap(~outcome, nrow = 1, scales = "free_x") +
  labs(x = "Estimate", y = "Intervention strategy")

print(graph5waves_marginal)

ggsave(graph5waves_marginal, file = here::here("figs", "graph5waves_marginal.png"), width = 10, height = 6)
```

## Mean difference

```{r 5wavesmi-graph-diff}
#| output: true
mod_5cummulative_mcs_diff <- readRDS(here::here("output", "model_5w_mcs_diff.rds"))

mod_5cummulative_pcs_diff <- readRDS(here::here("output", "model_5w_pcs_diff.rds"))

graph5waves_diff <- bind_rows(
  mod_5cummulative_mcs_diff |> filter(intervention != "0-0-0-0-0") |> mutate(outcome = "MCS"),
  mod_5cummulative_pcs_diff |> filter(intervention != "0-0-0-0-0") |> mutate(outcome = "PCS")
) |>
  mutate(
    n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |> factor(),
    intervention = str_replace_all(intervention, c("0" = "E", "1" = "U"))
  ) |>
  ggplot(aes(mi_effect, intervention, xmin = mi_ll, xmax = mi_ul, colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7)) +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_brewer(name = "Number of unemployed periods", palette = "Set1") +
  facet_wrap(~outcome, nrow = 1, scales = "free_x") +
  labs(x = "Estimate", y = "Intervention strategy")

print(graph5waves_diff)

ggsave(graph5waves_diff, file = here::here("figs", "graph5waves_diff.png"), width = 10, height = 6)
```