---
title: "Rapid Fire Presentation"
author: "Darwin Del Castillo"
format:
  html:
    toc: true
    fig-format: svg
execute:
  output: false
---

```{r env-setup}
#| output: false
#| message: false
options(max.print = 999999)
here::i_am("building_models/18_five_waves_final.qmd")

pacman::p_load(data.table, here, mice, gFormulaMI, magrittr, tidyverse, SPHSUgraphs, colorBlindness, patchwork, cowplot)
```

```{r four-waves-graph}
#| output: true
#| eval: false
#| include: false

mod_4cummulative_mcs_marginal <- readRDS(here::here("output", "model_4w_mcs_marginal.rds"))
mod_4cummulative_mcs_diff <- readRDS(here::here("output", "model_4w_mcs_diff.rds"))

graph4waves_marginal <- mod_4cummulative_mcs_marginal |> 
    mutate(outcome = "Mental Component Score (MCS)") |>
    mutate(n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |> factor(),
    intervention = str_replace_all(intervention, 
                                    c("0" = "E", "1" = "U"))) |>
  ggplot(aes(mi_effect, intervention, xmin = mi_ll, xmax = mi_ul, colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7)) +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_manual(values = unname(paletteMartin), name = "Number of unemployed periods") +
  facet_wrap(~outcome, nrow = 1, scales = "free_x") +
  labs(x = "Estimate", y = "Intervention strategy") +
  theme_bw()

print(graph4waves_marginal)

ggsave(here::here("figs", "conference", "graph4waves_marginal_conf.png"), graph4waves_marginal, width = 8, height = 5, dpi = 300)
```

```{r five-waves-graph}
mod_5cummulative_mcs_marginal <- readRDS(here::here("output", "model_5w_mcs_marginal.rds"))

graph5waves_marginal <- mod_5cummulative_mcs_marginal |> 
    mutate(outcome = "Mental Component Score (MCS)") |>
  mutate(
    n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |> factor(),
    intervention = str_replace_all(intervention, c("0" = "E", "1" = "U"))
  ) |>
  ggplot(aes(mi_effect, intervention, xmin = mi_ll, xmax = mi_ul, colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7)) +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_manual(values = unname(paletteMartin), name = "Number of unemployed periods") +
  facet_wrap(~outcome, nrow = 1, scales = "free_x") +
  scale_x_continuous(breaks = seq(44, 51, by = 1)) +
  labs(x = "Estimated marginal mean", y = "Intervention strategy") +
  theme_bw()

print(graph5waves_marginal)

ggsave(here::here("figs", "conference", "graph5waves_marginal_conf.png"), graph5waves_marginal, width = 8, height = 5, dpi = 300)
```

```{r three-waves-graph}
mod_3cummulative_mcs_marginal <- readRDS(here::here("output", "model_3w_mcs_marginal.rds"))

graph3waves_marginal <- mod_3cummulative_mcs_marginal |> mutate(outcome = "Mental Component Score (MCS)") |>
  mutate(
    n_unemp = map_int(intervention, ~ length(str_extract_all(.x, "1", simplify = TRUE))) |> factor(),
    intervention = str_replace_all(intervention, c("0" = "E", "1" = "U"))
  ) |>
  ggplot(aes(mi_effect, intervention, xmin = mi_ll, xmax = mi_ul, colour = n_unemp)) +
  geom_point(size = 2, position = position_dodge(width = 0.7)) +
  geom_errorbar(width = 0.3, position = position_dodge(width = 0.7)) +
  scale_colour_manual(values = unname(paletteMartin), name = "Number of unemployed periods") +
  facet_wrap(~outcome, nrow = 1, scales = "free_x") +
  scale_x_continuous(breaks = seq(44, 51, by = 1)) +
  labs(x = "Estimated marginal mean", y = "Intervention strategy") +
  theme_bw()

print(graph3waves_marginal)

ggsave(here::here("figs", "conference", "graph3waves_marginal_conf.png"), graph3waves_marginal, width = 8, height = 5, dpi = 300)
```