# _targets.R — pipeline orchestration for the employment and health outcomes
# from the HEED project, using gFormula via multiple imputation

library(targets)
library(tarchetypes)
library(future)
library(future.batchtools)
library(future.callr)

# Detect SLURM at runtime, if not in cluster, run locally with future.callr (in a separate r process)
on_slurm <- nzchar(Sys.getenv("SLURM_JOB_ID")) && nzchar(Sys.which("sbatch"))

if (on_slurm) {
  # Route batchtools worker registries under logs/ (default is ./.future). Each worker's
  # SLURM --output/--error is batchtools' log.file, which lives inside its registry, so
  # moving the registry root moves the worker logs too. getLog() still resolves — it reads
  # back the same path batchtools wrote as --output.
  options(future.cache.path = here::here("logs", ".future"))

  # future.batchtools 0.22.0 reads `resources` from the backend (the plan), NEVER
  # from per-target tar_resources_future(resources = ...). So each memory tier is a
  # separate tweaked plan, and targets swaps future::plan() per target via
  # tar_resources_future(plan = ...). slurm.tmpl uses whole-job --mem, so memory is
  # independent of ncpus. Tiers sized from local 3-wave timings (gform ~45 min,
  # mice ~23 min/outcome) with headroom for the 2^n_waves regime blow-up at 4/5 waves.
  slurm_tier <- function(memory_gb, walltime_h, ncpus = 2L) {
    future::tweak(
      future.batchtools::batchtools_slurm,
      template  = "slurm.tmpl",
      resources = list(
        ncpus    = ncpus,
        memory   = memory_gb * 1024L,       # MB, whole-job (--mem)
        walltime = walltime_h * 60L * 60L,  # seconds
        account  = "none"
      )
    )
  }
  plan_light <- slurm_tier(memory_gb = 24, walltime_h = 2)   # pop_data, build_data, graphs (m-independent)
  # Sizing from sacct MaxRSS/Elapsed of the m=200/maxit=10 run (job 2326426), five-wave = worst case.
  # Rerun is m=300, maxit=10 (unchanged) => mice ~linear in m only => x1.5. maxit affects runtime, never mem.
  # gform imps = m x 2^n_waves (unaffected by mice maxit; gform's internal mice is maxit=1) => x1.5 for m=300.
  plan_mice  <- slurm_tier(memory_gb = 24, walltime_h = 14)   # run_mice: peak 1.6G@m=200 -> ~2.4G; five-wave 6.8h x1.5 -> ~10.3h
  plan_gform <- slurm_tier(memory_gb = 224, walltime_h = 24)  # gFormulaImpute five-wave measured 112.9G/11.8h @m=200 -> ~169G/17.7h @m=300
  future::plan(plan_light)                                  # default for untagged targets
} else {
  # Off-cluster: one local plan; the plan_* names below just alias it so the
  # per-target tar_resources_future(plan = ...) tags are harmless locally.
  local_plan <- future::tweak(future.callr::callr, workers = 4L)
  plan_light <- plan_mice <- plan_gform <- local_plan
  future::plan(local_plan)
}

message("--- TARGETS FUTURE PLAN ---")
message("hostname:        ", Sys.info()[["nodename"]])
message("SLURM_JOB_ID:    '", Sys.getenv("SLURM_JOB_ID"), "'")
message("Sys.which sbatch: '", Sys.which("sbatch"), "'")
message("on_slurm:        ", on_slurm)
message("plan:            ", paste(class(future::plan()), collapse = "/"))
message("---------------------------")

# ---- Packages attached to every target's evaluation environment ----
tar_option_set(
  packages = c(
    "data.table",
    "bit64",
    "dplyr",
    "tidyr",
    "tibble",
    "purrr",
    "magrittr",
    "rlang",
    "here",
    "mice",
    "quarto",
    "gFormulaMI",
    "stringr",
    "fst",
    "lubridate",
    "haven",
    "ggplot2"
  ),
  format = "rds",
  repository = "local",
  storage   = "worker",   # workers read/write the shared _targets/ store directly, so
  retrieval = "worker",   # multi-GB gFormulaImpute objects never transit the controller
  seed   = 42
)

# ---- Source extracted functions (R/) ----
for (f in list.files(here::here("R"), pattern = "\\.R$", full.names = TRUE)) source(f); rm(f)

# ---- Configuration for each function ----
## mice configs
mice_m      <- 300
mice_maxit  <- 10
seed_random <- 42
## gFormulaMI configs
gform_M <- 300

# ---- Wave-set spec: one row per analysis, tar_map stamps the chain below per row ----
# how_many drives build_data's 2^n_intervention regimes; round_end = round_start + n_waves - 1.
# Add a wave-set here -> a full build->mice->gFormulaMI->results->plot chain appears in the DAG,
# target names suffixed by how_many (e.g. gform_mcs_three / _four / _five). Tier tags flow to all.
wave_spec <- tibble::tibble(
  how_many    = c("three", "four", "five"),
  round_start = c(3L, 3L, 3L),
  round_end   = c(5L, 6L, 7L)
)

# ---- Per-wave-set analysis chain (generated by tar_map) ----
mapped <- tar_map(
  values = wave_spec,
  names  = "how_many",

  # Build wide datasets (MCS / PCS) -- light tier (default plan)
  tar_target(wide_data_mcs,
    build_data(data = pop_data, how_many = how_many, outcome = "MCS",
               round_start = round_start, round_end = round_end)),
  tar_target(wide_data_pcs,
    build_data(data = pop_data, how_many = how_many, outcome = "PCS",
               round_start = round_start, round_end = round_end)),

  # mice imputation (m = 100) -- mice tier
  tar_target(wide_mids_mcs,
    run_mice(wide_data = wide_data_mcs$data, m = mice_m, maxit = mice_maxit, seed = seed_random),
    resources = tar_resources(future = tar_resources_future(plan = plan_mice))),
  tar_target(wide_mids_pcs,
    run_mice(wide_data = wide_data_pcs$data, m = mice_m, maxit = mice_maxit, seed = seed_random),
    resources = tar_resources(future = tar_resources_future(plan = plan_mice))),

  # gFormulaMI: marginal + ATE, both outcomes -- gform tier
  tar_target(gform_mcs,
    run_gform(wide_mids = wide_mids_mcs, wide_data_mi = wide_data_mcs$data,
              intervention_pattern = wide_data_mcs$intervention_pattern,
              estimand = "factor(regime) + 0", M = gform_M),
    resources = tar_resources(future = tar_resources_future(plan = plan_gform))),
  tar_target(gform_pcs,
    run_gform(wide_mids = wide_mids_pcs, wide_data_mi = wide_data_pcs$data,
              intervention_pattern = wide_data_pcs$intervention_pattern,
              estimand = "factor(regime) + 0", M = gform_M),
    resources = tar_resources(future = tar_resources_future(plan = plan_gform))),
  tar_target(gform_mcs_ate,
    run_gform(wide_mids = wide_mids_mcs, wide_data_mi = wide_data_mcs$data,
              intervention_pattern = wide_data_mcs$intervention_pattern,
              estimand = "factor(regime)", M = gform_M),
    resources = tar_resources(future = tar_resources_future(plan = plan_gform))),
  tar_target(gform_pcs_ate,
    run_gform(wide_mids = wide_mids_pcs, wide_data_mi = wide_data_pcs$data,
              intervention_pattern = wide_data_pcs$intervention_pattern,
              estimand = "factor(regime)", M = gform_M),
    resources = tar_resources(future = tar_resources_future(plan = plan_gform))),

  # Plots: run_gform returns only the small results tibble (imps never persist), so
  # gform_* objects are light -> plot reads them directly on the light tier, no
  # extraction layer needed. Stays light at any wave count.
  tar_target(graphs,
    make_graphs(
      gform_mcs     = gform_mcs,
      gform_pcs     = gform_pcs,
      gform_mcs_ate = gform_mcs_ate,
      gform_pcs_ate = gform_pcs_ate,
      mcs_label = "Mental Component Score (MCS)",
      pcs_label = "Physical Component Score (PCS)",
      save_dir  = here::here("figs"),
      wave_label = how_many
    ))
)

# ---- Pipeline: shared import + the mapped per-wave-set chains ----
list(
  # Data preparation: import, clean, preprocessing (shared across every wave-set).
  tar_target(pop_data,
    if (on_slurm) {
      import_data(force = FALSE) |> clean_data() |> preproc_data()
    } else {
      import_data(force = TRUE) |> clean_data() |> preproc_data()
    }),
  mapped
)