library(haven)
library(tidyverse)
library(gfoRmula)


# TODO add intdaty_lag?

data_in <- read_stata("T:/projects/HEED/Data/USoc prepared data/Test_Harry14.dta")
data <- data_in |>
  select(-age_sq)

data <-
  data |>
  filter(wave >= 6) |> 
  mutate(
    across(c(pidp, ppid, hidp, wave, pns1pid, pns2pid),
           as.integer),
    across(where(haven::is.labelled),
           haven::zap_labels),
    wnw_race = case_when(racel_dv %in% 1:4 ~ 0, racel_dv %in% 5:97 ~  1, .default = NA),
    econ_emp_bin = case_when(econ_emp == 1 ~ 0, econ_emp == 3 ~ 1),
    t0 = wave - 6)
  # mutate(
  #   t0 = wave - min(wave),
  #   .by = pidp
  # )

age_correctors <- data |> 
  filter(!is.na(age_dv)) |> 
  summarise(base_age = mean(age_dv - t0) |> round(), .by = pidp)

expanded_data <- data |>
  filter(!is.na(age_dv)) |> 
  select(pidp) |> 
  unique() |> 
  slice_sample(n = 2000) |> 
  expand_grid(tibble(t0 = 0:4)) |> 
  unique() |> 
  left_join(data)

expanded_data <- expanded_data |> 
  inner_join(age_correctors, by = "pidp") |> 
  mutate(age_dv = base_age)


###################

outcome_type <- "continuous_eof"

covnames <-
  c(
    "sf12pcs_dv",
    "log_income",
    "econ_emp_bin",
    "econ_dist",
    "ghqcase4",
    "home_owner",  # Added with prediction model
    "mastat_dv",
    "gor_dv",
    "dnc"
  )

outcome_name <- "sf12pcs_dv"
intvars <- c("econ_emp_bin")

covtypes <- c("normal", # sf12pcs_dv
              "normal", # log_income
              "binary", # econ_emp_bin
              "binary", # econ_dist
              "binary", # ghqcase4
              "binary", # home_owner
              "categorical", # mastat_dv
              "categorical", # gor_dv
              "categorical" # dnc
              # TODO find a way to deal with ordinal variables
              )
# TODO verify the methods are valid

basecovs <- c("sex_dv", "age_dv", "hiqual_dv")


covparams <- list(
  covmodels = c(
    sf12pcs_dv ~ sex_dv + hiqual_dv +
      lag1_sf12pcs_dv + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income +
      lag1_econ_emp_bin + lag1_econ_dist +
      t0,
    log_income ~ lag1_log_income + sf12pcs_dv +
      stats::poly(age_dv, 2) + hiqual_dv +
      econ_emp_bin + home_owner + mastat_dv + dnc +
      ghqcase4 + gor_dv + lag1_dnc + lag1_ghqcase4 +
      t0,
    econ_emp_bin ~ sex_dv + hiqual_dv + 
      stats::poly(age_dv, 2) + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income + sf12pcs_dv +
      lag1_econ_dist + t0,
    econ_dist ~ sex_dv + hiqual_dv + 
      stats::poly(age_dv, 2) + home_owner + mastat_dv +
      dnc + gor_dv + ghqcase4 + log_income +
      econ_emp_bin + t0,
    ghqcase4 ~ sex_dv + stats::poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + t0,
    home_owner ~ sex_dv + hiqual_dv + 
      stats::poly(age_dv, 2) + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income + sf12pcs_dv +
      lag1_econ_dist + t0,
    mastat_dv ~ sex_dv + stats::poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + t0,
    gor_dv ~ sex_dv + stats::poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + t0,
    dnc ~ sex_dv + stats::poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + t0
  )
)

# covpredict_custom <- c(
#   rep(NA, length(covparams$covmodels) - 1),
#   \() lag1_intdaty_dv + 1
# )


lagged_variables <- c("econ_emp_bin",
                      "home_owner",
                      "mastat_dv",
                      "dnc",
                      "gor_dv",
                      "ghqcase4",
                      "log_income",
                      "econ_dist",
                      "sf12pcs_dv"
)

histories <- c(lagged) # TODO replace plm lags with autogenerated ones
histvars <- list(lagged_variables)
# TODO write history for diffs, see C.8

nsimul <- 100 # Monte Carlo sample size
ncores <- parallel::detectCores() - 1

ymodel <- sf12pcs_dv ~  sex_dv + stats::poly(age_dv, 2) + hiqual_dv +
  lag1_sf12pcs_dv + home_owner + lag1_home_owner + mastat_dv + lag1_mastat_dv +
  dnc + lag1_dnc + gor_dv + lag1_gor_dv + ghqcase4 + lag1_ghqcase4 +
  log_income + lag1_log_income + econ_emp_bin + lag1_econ_emp_bin + econ_dist +
  lag1_econ_dist #  if wave>=7 
# TODO add proper wave handling


intvars <- as.list(rep("econ_emp_bin", 8))

interventions <- tibble(econ_emp_bin1 = 0:1,
                        econ_emp_bin2 = 0:1,
                        econ_emp_bin3 = 0:1) |> 
  expand.grid() |> 
  t() |>
  rbind(matrix(0, nrow = 2, ncol = 8), x = _) |> 
  as_tibble() |>
    unclass() |>
    map(~list(c(static, .x)))

int_description <-
  map(interventions, ~paste(.x[[1]][2:5], collapse = "-") |> paste0("econ_emp_bin:", x = _))

time_points <- length(unique(data$t0))

gform_cont_eof <- gformula(obs_data = expanded_data,
                          outcome_type = outcome_type,
                          id = "pidp",
                          time_name = "t0",
                          time_points = time_points,
                          covnames = covnames,
                          outcome_name = outcome_name,
                          covtypes = covtypes,
                          covparams = covparams,
                          # covpredict_custom = covpredict_custom,
                          ymodel = ymodel,
                          
                          intvars = intvars,
                          interventions = interventions,
                          int_descript = int_description,
                          
                          histories = histories,
                          histvars = histvars,
                          basecovs = basecovs,
                          seed = 1234,
                          parallel = FALSE,
                          # nsamples = 200, # Number of bootstrap samples 
                          nsimul = nsimul)
