library(haven)
library(dplyr)
library(plm)
library(gfoRmula)

lagged_variables <- c("econ_emp",
                      "intdaty_dv",
                      "home_owner",
                      "mastat_dv",
                      "dnc",
                      "gor_dv",
                      "ghqcase4",
                      "log_income",
                      "econ_dist",
                      "sf12pcs_dv"
)
# TODO add intdaty_lag?

data <- read_stata("T:/projects/HEED/Data/USoc prepared data/Test_Harry14.dta")
data <- data |> select(-age_sq) # we generate age_sq when needed

data <-
  data |>
  mutate(across(c(pidp, ppid, hidp, wave, pns1pid, pns2pid),
                as.integer),
         across(where(haven::is.labelled),
                haven::zap_labels))

raw_columns <- c(
  "jbhrs",
  "jshrs",
  "j2hrs",
  "fimnlabgrs_dv",
  "fiyrinvinc_dv",
  "sf12pcs_dv",
  "sf12mcs_dv",
  "fihhmnnet1_dv",
  "fihhmnsben_dv",
  "ieqmoecd_dv",
  "_merge",
  "depChild",
  "depChild2"
)

panel_data <- pdata.frame(data, c('pidp', 'wave'))

if (length(lagged_variables) == 1) {
  panel_data[paste("lag1", lagged_variables[1], sep = "_")] <- plm::lag(panel_data[, lagged_variables])
} else {
  for (column_name in lagged_variables) {
    panel_data[paste("lag1", column_name, sep = "_")] <- plm::lag(panel_data[, c(column_name)])
  }
  #lags <- data.frame(lapply(as.list(panel_data[, lagged_variables], keep.attributes = TRUE), plm::lag))
  #colnames(lags) <- paste(colnames(lags), "lag1", sep = "_")
  #panel_data <- cbind(panel_data, lags)
}
# TODO make sure there is no OPCODEs in these variables

data <- as.data.frame(panel_data)

# 0 "Emp_both"
# 1 "Emp_stu"
# 2 "Emp_notemp" 
# 3 "Emp_ret" 
# 4 "Stu_emp" 
# 5 "Stu_both" 
# 6 "Stu_notemp" 
# 7 "Stu_ret" 
# 8 "Notemp_emp" 
# 9 "Notemp_stu" 
# 10 "Notemp_both" 
# 11 "Notemp_ret" 
# 12 "Ret_emp" 
# 13 "Ret_stu" 
# 14 "Ret_nonemp" 
# 15 "Ret_both"

data <- data |> mutate(
  lag1_econ_econ = (econ_emp - 1) * 4 + lag1_econ_emp - 1,
wnw_race = ifelse(racel_dv %in% 1:4, 0, ifelse(racel_dv %in% 5:97, 1, NA)),
econ_emp_bin = case_when(econ_emp == 1 ~ 0, econ_emp == 3 ~ 1)
)

panel_data <- pdata.frame(data, c('pidp', 'wave'))
panel_data["lag1_econ_emp_bin"] <- plm::lag(panel_data[, c("econ_emp_bin")])
data <- as.data.frame(panel_data)


###################################
#bysort	pidp:	gen	cum_emp=sum(econ_emp_bin)
#gen Lcum_emp=L.cum_emp

data <- data[data$age_dv <= 65 & data$age_dv >= 25, ]
data <- data |> mutate(ukcount = case_when(gor_dv <= 10 & gor_dv >= 1~ 1, gor_dv == 11 ~ 2, gor_dv == 12 ~ 3, gor_dv == 13 ~ 4))

panel_data <- pdata.frame(data, c('pidp', 'wave'))
panel_data["lag1_ukcount"] <- plm::lag(panel_data[, c("ukcount")])
data <- as.data.frame(panel_data)

###################

outcome_type <- "continuous_eof"
covnames <-
  c(
    "sf12pcs_dv",
    "log_income",
    "econ_emp_bin",
    "econ_dist",
    "ghqcase4",
    "mastat_dv",
    "gor_dv",
    "dnc"
  )
outcome_name <- "sf12pcs_dv"
intvars <- c("econ_emp_bin")

covtypes <- c("normal", # sf12pcs_dv
              "normal", # log_income
              "binary", # econ_emp_bin
              "binary", # econ_dist
              "binary", # ghqcase4
              "categorical", # mastat_dv
              "categorical", # gor_dv
              "categorical" # dnc
              # TODO find a way to deal with ordinal variables
              )
# TODO verify the methods are valid

basecovs <- c("sex_dv")

histories <- c(lagged) # TODO replace plm lags with autogenerated ones
histvars <- list(lagged_variables)
# TODO write history for diffs, see C.8

nsimul <- 10000 # Monte Carlo sample size
ncores <- parallel::detectCores() - 1

covparams <- list(
  covmodels = c(
    sf12pcs_dv ~ sex_dv + hiqual_dv +
      lag1_sf12pcs_dv + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income +
      lag1_econ_emp_bin + lag1_econ_dist +
      intdaty_dv,
    log_income ~ lag1_log_income + sf12pcs_dv +
      age_dv + poly(age_dv, 2) + hiqual_dv +
      econ_emp_bin + home_owner + mastat_dv + dnc +
      ghqcase4 + gor_dv + lag1_dnc + lag1_ghqcase4 +
      intdaty_dv,
    econ_emp_bin ~ sex_dv + hiqual_dv + age_dv +
      poly(age_dv, 2) + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income + sf12pcs_dv +
      lag1_econ_dist + lag1_intdaty_dv,
    econ_dist ~ sex_dv + hiqual_dv + age_dv +
      poly(age_dv, 2) + home_owner + mastat_dv +
      dnc + gor_dv + ghqcase4 log_income +
      econ_emp_bin + intdaty_dv,
    ghqcase4 ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_Lmastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    mastat_dv ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    gor_dv ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    dnc ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
  )
)

ymodel <- sf12pcs_dv ~  sex_dv + age_dv + poly(age_dv, 2) + hiqual_dv +
  lag1_sf12pcs_dv + home_owner + lag1_home_owner + mastat_dv + lag1_mastat_dv +
  dnc + lag1_dnc + gor_dv + lag1_gor_dv + ghqcase4 + lag1_ghqcase4 +
  log_income + lag1_log_income + econ_emp_bin + lag1_econ_emp_bin + econ_dist +
  lag1_econ_dist + intdaty_dv + intdaty_lag + wave #  if wave>=7 
# TODO add proper wave handling

gform_bin_eof <- gformula(obs_data = binary_eofdata,
                          outcome_type = outcome_type,
                          id = 'pidp',
                          time_name = 'wave',
                          covnames = covnames,
                          outcome_name = outcome_name,
                          covtypes = covtypes,
                          covparams = covparams,
                          ymodel = ymodel,
                          
                          intvars = NULL, # FIXME
                          interventions = NULL, # FIXME
                          int_descript = NULL, # FIXME
                          
                          histories = histories,
                          histvars = histvars,
                          basecovs = basecovs,
                          seed = 1234,
                          parallel = TRUE,
                          nsamples = 20, # Number of bootstrap samples 
                          nsimul = nsimul,
                          ncores = ncores)
