library(haven)
library(dplyr)
library(plm)
library(gfoRmula)

lagged_variables <- c("econ_emp_bin",
                      "intdaty_dv",
                      "home_owner",
                      "mastat_dv",
                      "dnc",
                      "gor_dv",
                      "ghqcase4",
                      "log_income",
                      "econ_dist",
                      "sf12pcs_dv"
)
# TODO add intdaty_lag?

data <- read_stata("T:/projects/HEED/Data/USoc prepared data/Test_Harry14.dta")
data <- data |>
  select(-age_sq)  |> 
  mutate(
    wnw_race = case_when(racel_dv %in% 1:4 ~ 0, racel_dv %in% 5:97 ~  1, .default = NA),
    econ_emp_bin = case_when(econ_emp == 1 ~ 0, econ_emp == 3 ~ 1)
  )

data <-
  data |>
  mutate(across(c(pidp, ppid, hidp, wave, pns1pid, pns2pid),
                as.integer),
         across(where(haven::is.labelled),
                haven::zap_labels))

# raw_columns <- c(
#   "jbhrs",
#   "jshrs",
#   "j2hrs",
#   "fimnlabgrs_dv",
#   "fiyrinvinc_dv",
#   "sf12pcs_dv",
#   "sf12mcs_dv",
#   "fihhmnnet1_dv",
#   "fihhmnsben_dv",
#   "ieqmoecd_dv",
#   "_merge",
#   "depChild",
#   "depChild2"
# )

###################

outcome_type <- "continuous_eof"
covnames <-
  c(
    "sf12pcs_dv",
    "log_income",
    "econ_emp_bin",
    "econ_dist",
    "ghqcase4",
    "mastat_dv",
    "gor_dv",
    "dnc"
  )
outcome_name <- "sf12pcs_dv"
intvars <- c("econ_emp_bin")

covtypes <- c("normal", # sf12pcs_dv
              "normal", # log_income
              "binary", # econ_emp_bin
              "binary", # econ_dist
              "binary", # ghqcase4
              "categorical", # mastat_dv
              "categorical", # gor_dv
              "categorical" # dnc
              # TODO find a way to deal with ordinal variables
              )
# TODO verify the methods are valid

basecovs <- c("sex_dv")

histories <- c(lagged) # TODO replace plm lags with autogenerated ones
histvars <- list(lagged_variables)
# TODO write history for diffs, see C.8

nsimul <- 10000 # Monte Carlo sample size
ncores <- parallel::detectCores() - 1

covparams <- list(
  covmodels = c(
    sf12pcs_dv ~ sex_dv + hiqual_dv +
      lag1_sf12pcs_dv + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income +
      lag1_econ_emp_bin + lag1_econ_dist +
      intdaty_dv,
    log_income ~ lag1_log_income + sf12pcs_dv +
      age_dv + poly(age_dv, 2) + hiqual_dv +
      econ_emp_bin + home_owner + mastat_dv + dnc +
      ghqcase4 + gor_dv + lag1_dnc + lag1_ghqcase4 +
      intdaty_dv,
    econ_emp_bin ~ sex_dv + hiqual_dv + age_dv +
      poly(age_dv, 2) + lag1_home_owner +
      lag1_mastat_dv + lag1_dnc + lag1_gor_dv +
      lag1_ghqcase4 + lag1_log_income + sf12pcs_dv +
      lag1_econ_dist + lag1_intdaty_dv,
    econ_dist ~ sex_dv + hiqual_dv + age_dv +
      poly(age_dv, 2) + home_owner + mastat_dv +
      dnc + gor_dv + ghqcase4 log_income +
      econ_emp_bin + intdaty_dv,
    ghqcase4 ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_Lmastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    mastat_dv ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    gor_dv ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
    dnc ~ sex_dv + age_dv + poly(age_dv, 2) +
      hiqual_dv + lag1_ghqcase4 + lag1_sf12pcs_dv +
      lag1_home_owner + lag1_mastat_dv + lag1_dnc +
      lag1_gor_dv + lag1_log_income +
      lag1_econ_emp_bin + econ_emp_bin +
      lag1_econ_dist + econ_dist + intdaty_lag,
  )
)

ymodel <- sf12pcs_dv ~  sex_dv + age_dv + poly(age_dv, 2) + hiqual_dv +
  lag1_sf12pcs_dv + home_owner + lag1_home_owner + mastat_dv + lag1_mastat_dv +
  dnc + lag1_dnc + gor_dv + lag1_gor_dv + ghqcase4 + lag1_ghqcase4 +
  log_income + lag1_log_income + econ_emp_bin + lag1_econ_emp_bin + econ_dist +
  lag1_econ_dist + intdaty_dv + intdaty_lag + wave #  if wave>=7 
# TODO add proper wave handling

gform_bin_eof <- gformula(obs_data = binary_eofdata,
                          outcome_type = outcome_type,
                          id = 'pidp',
                          time_name = 'wave',
                          covnames = covnames,
                          outcome_name = outcome_name,
                          covtypes = covtypes,
                          covparams = covparams,
                          ymodel = ymodel,
                          
                          intvars = NULL, # FIXME
                          interventions = NULL, # FIXME
                          int_descript = NULL, # FIXME
                          
                          histories = histories,
                          histvars = histvars,
                          basecovs = basecovs,
                          seed = 1234,
                          parallel = TRUE,
                          nsamples = 20, # Number of bootstrap samples 
                          nsimul = nsimul,
                          ncores = ncores)
