---
title: "GFormula comparisons"
format: 
  docx:
    number-sections: true
editor: visual
---

# Reading in data

```{r}
#| output: false
library(gfoRmula)
library(magrittr)
library(DiagrammeR)
source("R/data_import_and_cleaning.R")
```

# Simple version - two time-points

```{r}
# All observations with complete data across waves 9 and 10
late_pop <-
  pop_data[wave %in% 9:10][, `:=`(t0 = t0 - 3)]

missings <-
  late_pop[is.na(sf12mcs_dv) |
             is.na(sf12pcs_dv) | is.na(sex_dv_base) |
             is.na(econ_emp_bin), .(pidp)]

late_pop <- late_pop[!missings, on = .(pidp)]
```

## `gformula`

Four interventions, unemployment (1) at times 1 or 2:

-   Intervention 1: econ_emp_bin=0-0
-   Intervention 2: econ_emp_bin=1-0
-   Intervention 3: econ_emp_bin=0-1
-   Intervention 4: econ_emp_bin=1-1

Outcome: MCS Baseline covariates: sex Time-varying covariates: PCS

```{r}
#| echo: false

grViz("digraph {
  graph []
  node [fontname=Arial]
  A1 [label=<Empl<SUB>0</SUB>>]
  A2 [label=<Empl<SUB>1</SUB>>]
  L1 [label=<PCS<SUB>0</SUB>>]
  L2 [label=<PCS<SUB>1</SUB>>]
  Y [label='MCS']
  S [label='Sex', color=grey]
  X [label='', color=none]
  edge []
  S -> A1, A2, L1, L2, Y [color=grey]
  A1 -> A2
  A2 -> X -> Y [color=none]
  A1 -> Y
  L1 -> L2, A2 -> Y
  L1 -> A1 -> L2 -> A2
  {rank = same; L1; L2; Y}
  {rank = same; A1; A2; X}
  {rank = min; L1; L2; Y}
  {rank = max; S}
}")
```

```{r}
outcome_type <- "continuous_eof"

covnames <-
  c(
    "econ_emp_bin",
    "sf12pcs_dv"
  )

outcome_name <- "sf12mcs_dv"
intvars <- c("econ_emp_bin")

covtypes <- c(
  "binary", # econ_emp_bin
  "normal" # sf12pcs_dv
)

basecovs <- c(
  "sex_dv_base"
)

ymodel <- sf12mcs_dv ~  sex_dv_base +  # Baseline - sex
  sf12pcs_dv + lag1_sf12pcs_dv +       # Time-varying confounders
  econ_emp_bin + lag1_econ_emp_bin     # Time-varying exposures


covparams <- list(
  covmodels = c(
    econ_emp_bin ~ sex_dv_base +
      sf12pcs_dv + lag1_sf12pcs_dv + 
      lag1_econ_emp_bin,
    sf12pcs_dv ~ sex_dv_base +
      lag1_sf12pcs_dv + 
      lag1_econ_emp_bin
  )
)

# laggedvars(Lsf12mcs_dv Lsf12pcs_dv Lage_dv Llog_income Lecon_emp_bin Lecon_dist intdaty_lag)

lagged_variables <- c(
  "sf12pcs_dv",
  "econ_emp_bin"
)


histories <- c(lagged)
histvars <- list(lagged_variables)

nsimul <- 2000 # Monte Carlo sample size
ncores <- min(32, parallel::detectCores() - 1)



interventions <- expand_grid(econ_emp_bin1 = 0:1,
                        econ_emp_bin2 = 0:1) |> 
  t() |>
  as_tibble(.name_repair = "minimal") |>
  unclass() |>
  map(~list(c(static, .x)))

intvars <- as.list(rep("econ_emp_bin", length(interventions)))

int_description <-
  map(interventions, ~paste(.x[[1]][-1], collapse = "-") |> paste0("econ_emp_bin:", x = _))

time_points <- 2

gform_cont_eof <- gformula(obs_data = late_pop,
                           outcome_type = outcome_type,
                           id = "pidp",
                           time_name = "t0",
                           time_points = time_points,
                           covnames = covnames,
                           outcome_name = outcome_name,
                           covtypes = covtypes,
                           covparams = covparams,
                           # covpredict_custom = covpredict_custom,
                           ymodel = ymodel,
                           
                           intvars = intvars,
                           interventions = interventions,
                           int_descript = int_description,
                           
                           histories = histories,
                           histvars = histvars,
                           basecovs = basecovs,
                           seed = 1234,
                           parallel = FALSE,
                           # nsamples = 200, # Number of bootstrap samples
                           # nsimul = nsimul,
                           ref_int = 1
)

```

## Manually calculating

Reshape and rename:

```{r}
pop_df <- as_tibble(late_pop) |> 
  select(-wave) |> 
  pivot_wider(id_cols = c(pidp, ends_with("base")), names_from = t0, values_from = sf12mcs_dv:econ_dist) |> 
  select(
    Y = sf12mcs_dv_1,
    A1 = econ_emp_bin_0,
    A2 = econ_emp_bin_1,
    L1 = sf12pcs_dv_0,
    L2 = sf12pcs_dv_1,
    sex = sex_dv_base
  )
```

```{r}
#| echo: false
grViz("digraph {
  graph []
  node [fontname=Arial]
  A1 
  A2 
  L1 
  L2 
  Y 
  X [label='', color=none]
  edge []
  A1 -> A2
  A1 -> Y
  L1 -> L2, A2 -> Y
  A2 -> X -> Y [color=none]
  L1 -> A1 -> L2 -> A2
  {rank = same; L1; L2; Y}
  {rank = same; A1; A2; X}
  {rank = min; L1; L2; Y}
}")
```

```{r}
main_mod <- lm(Y ~ sex + L1 + A1 + L2 + A2, data = pop_df)

# All intervention populations set up
data_to_test <- expand_grid(A1 = 0:1, A2 = 0:1) |> 
  mutate(
    intervention = paste(A1, A2, sep = "-"),
    data_newvals = map2(A1, A2, \(a1, a2) mutate(pop_df, A1 = a1, A2 = a2))
  ) |> 
  bind_rows(
    tibble(intervention = "natural", data_newvals = list(pop_df)),
    x = _
  ) |> 
select(-A1, -A2)

# Model to update time-varying covariate L at T=2
modl2 <- pop_df %$%
  lm(L2 ~ sex + L1 + A1)


manual_results <- data_to_test |> 
  mutate(
    # Predict confounder at t2 based on t1 vars
    data_update = map(data_newvals, ~mutate(.x, L2 = predict(modl2, newdata = .x))),
    # re-do predicton from main model based on updated L2s
    outcomes = map(data_update, ~predict(main_mod, newdata = .x)),
    # means of new values
    manual_result = map_dbl(outcomes, mean)
  ) |> 
  select(intervention, manual_result) 
```

## MI method

```{r}

library(gFormulaMI)

regimes <- tibble(a = 0:1, b = 0:1) |>
  expand.grid() |>
  arrange(a, b) |>
  t() |>
  as_tibble() |>
  unclass() |> unname()


pred_matrix <- matrix(c(
  0, 0, 1, 1, 1, 1, 1,
  0, 0, 1, 1, 1, 1, 1,
  0, 0, 0, 1, 1, 1, 1,
  0, 0, 0, 0, 1, 1, 1, 
  0, 0, 0, 0, 0, 1, 1, 
  0, 0, 0, 0, 0, 0, 1,
  0, 0, 0, 0, 0, 0, 0),
  nrow = 7, ncol = 7,
  dimnames = list(
    c("sex", "L1", "L2", "A1", "A2", "Y", "regime"),
    c("sex", "L1", "L2", "A1", "A2", "Y", "regime")
  ))

imps <- gFormulaImpute(
  pop_df |> select(sex, L1, L2, A1, A2, Y),
  M = 20,
  trtVars = c("A1", "A2"),
  trtRegimes = regimes,
  predictorMatrix = pred_matrix
)


fits <- imps %$%
  lm(Y ~ factor(regime))

outvals <- syntheticPool(fits)

mi_results <-
  outvals |>
  as_tibble() |>
  rownames_to_column("Intervention") |>
  transmute(MI_result = ifelse(Intervention == 1,
                               Estimate,
                               Estimate[Intervention == 1] + Estimate)) |> 
  bind_rows(tibble(MI_result = NA_real_), x = _)

```


## Comparing results

```{r}

gform_cont_eof$result |> 
  select(`g-form mean`) |>
  bind_cols(mi_results) |> 
  bind_cols(manual_results, x = _) |> 
  knitr::kable(digits = 3)
  
```

